sudo: required

cache:
  directories:
    - "$HOME/.m2"

language: java

notifications:
  email: false
  on_failure: never

addons:
  apt:
    sources:
      - ubuntugis/ubuntugis-unstable
      - george-edison55/precise-backports
    packages:
      - cmake
      - libgmp3-dev
      - libmpfr-dev

before_install:
  - ./travis/${TRAVIS_OS_NAME}/before_install.sh

script :
  - mvn clean install

jdk:
  - oraclejdk8
