sudo: required

cache:
  directories:
    - "$HOME/.m2"
    
language: java

notifications:
  email: false
  on_failure: never
  
before_script :
  - chmod +x ./travis/${TRAVIS_OS_NAME}/before_install.sh

script :
  - ./travis/${TRAVIS_OS_NAME}/before_install.sh
  - mvn clean install

jdk: 
  - oraclejdk8
