sudo: required

cache:
  directories:
    - "$HOME/.m2"
    - "/usr/local/"
    
language: java

script:
  - mvn -B -fae -Djava.awt.headless=true -Dall clean install
  
notifications:
  email: false
  on_failure: never
  
before_script :
  - chmod +x ./travis/${TRAVIS_OS_NAME}/before_install.sh

script :
  - ./travis/${TRAVIS_OS_NAME}/before_install.sh

jdk: 
  - oraclejdk8
