sudo: required

cache:
  directories:
    - "$HOME/.m2"
    
language: java

notifications:
  email: false
  on_failure: never

before_install:
	sudo apt-get -qq update
	sudo apt-get install -y libboost-dev libgmp3-dev libmpfr-dev libcgal-dev libsfcgal-dev
  
script:
