sudo: required

cache:
  directories:
    - "$HOME/.m2"

language: java

notifications:
  email: false
  on_failure: never

before_script:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y cmake libboost-dev libgmp3-dev libmpfr-dev libcgal-dev

script :
   - ./travis/${TRAVIS_OS_NAME}/before_install.sh
   - mvn clean install

jdk:
  - oraclejdk8
