sudo: required

cache:
  directories:
    - "$HOME/.m2"

language: java

notifications:
  email: false
  on_failure: never

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake
  - cmake --version
  - ./unsupported/geometry-ng/cppbuild.sh install

script :
  - mvn clean install

jdk:
  - oraclejdk8
