sudo: required

cache:
  directories:
    - "$HOME/.m2"
    
language: java

notifications:
  email: false
  on_failure: never

services:
  - docker

before_install:
  - docker pull hgryoo/geoserver-3d-extension-environment
  - docker run hgryoo/geoserver-3d-extension-environment
  
script:
  - mvn clean install

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push STEMLab/geotools-3d-extension;
    fi