sudo: required

cache:
  directories:
    - "$HOME/.m2"

language: java

notifications:
  email: false
  on_failure: never

before_install:
  - sudo add-apt-repository -y ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y george-edison55/precise-backports
  - sudo apt-get install -y cmake libgmp3-dev libmpfr-dev
  - ./travis/${TRAVIS_OS_NAME}/before_install.sh

script :
  - mvn clean install

jdk:
  - oraclejdk8
